server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
    dbcp2:
      test-while-idle: true
      test-on-borrow: true
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: xxx
            clientSecret: xxx
            scope:
              - email
              - profile
  mail:
    host: host111.ni.net.tr
    port: 587
    username: noreplay@localhost
    password: xxxxx
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

app:
  securityEnabled: true
  redisServerHost: redishost
  redisServerPassword: redispass
